version: 2
updates:
  - package-ecosystem: npm
    directory: .
    open-pull-requests-limit: 40
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /examples
    open-pull-requests-limit: 40
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: weekly