version: 2
updates:
  - package-ecosystem: npm
    directory: .
    open-pull-requests-limit: 40
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "bun-plugin-dts" #seems broken after 0.2.1
  - package-ecosystem: npm
    directory: /examples
    open-pull-requests-limit: 40
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: weekly