name: build-examples

on:
  push:
    branches: [ master ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
        working-directory: ./examples
      - run: npm run build:examples
        working-directory: ./examples
      - run: npm run test:examples
        working-directory: ./examples

  build-next:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
        working-directory: ./main
      - run: npm run build:use-sortablejs
        working-directory: ./main
      - run: npm run preinstall:next
        working-directory: ./examples
      - run: npm i
        working-directory: ./examples
      - run: npm run build:examples:next
        working-directory: ./examples
      - run: npm run test:examples
        working-directory: ./examples